# Generated by Django 4.1.7 on 2023-03-26 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=50, verbose_name='Notice Subject')),
                ('notice_date', models.DateField(verbose_name='Notice Date')),
                ('upload_on', models.DateTimeField(auto_now_add=True, verbose_name='Notice Upload Date')),
                ('notice_copy', models.FileField(upload_to='Notices/', verbose_name='Notice Copy')),
                ('upload_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'ordering': ['-notice_date'],
            },
        ),
    ]
